version: '3.8'

services:
  mssql_mcp_server:
    image: tsviz/mssql-mcp-server:123
    build: .
    ports:
      - "8000:8000"
    environment:
      MSSQL_SERVER: server_name_or_ip
      MSSQL_USER: your_username
      MSSQL_PASSWORD: YourNewStrongPassword
      MSSQL_PORT: 1433
      MSSQL_DATABASE: your_database_name
    volumes:
      - .:/app